global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoApp11.DataContracts;
global using UnoApp11.DataContracts.Serialization;
global using UnoApp11.Models;
global using UnoApp11.Presentation;
global using UnoApp11.Services.Caching;
global using UnoApp11.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
